version: 2

defaults: &defaults
  docker:
    - image: codegram/decidim
      environment:
        SIMPLECOV: true
        DATABASE_USERNAME: postgres
    - image: postgres
      environment:
        POSTGRES_USER: postgres
  working_directory: /code

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - checkout
      - run:
          name: Install app dependencies
          command: |
            bundle install
            npm i
      - run:
          name: Generate test app
          command: bundle exec rake decidim:generate_test_app
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  main:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Install dependencies
          command: gem install decidim
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run main folder npm lint
          command: time npm run lint
      - run:
          name: Run main folder RSpec
          command: time bundle exec rspec
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  core:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run core JS tests
          command: ./.circleci/run_tests.sh decidim-core "time npm test -- decidim-core"
      - run:
          name: Run core RSpec
          command: ./circleci/run_tests.sh decidim-core "cd decidim-core && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  assemblies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run assemblies JS tests
          command: ./.circleci/run_tests.sh decidim-assemblies "time npm test -- decidim-assemblies"
      - run:
          name: Run assemblies RSpec
          command: ./.circleci/run_tests.sh decidim-assemblies "cd decidim-assemblies && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  api:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run api JS tests
          command: ./.circleci/run_tests.sh decidim-api "time npm test -- decidim-api"
      - run:
          name: Run api RSpec
          command: ./.circleci/run_tests.sh decidim-api "cd decidim-api && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  processes:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run participatory_processes JS tests
          command: ./.circleci/run_tests.sh decidim-participatory_processes "time npm test -- decidim-participatory_processes"
      - run:
          name: Run participatory_processes RSpec
          command: ./.circleci/run_tests.sh decidim-participatory_processes "cd decidim-participatory_processes && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  admin:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run admin JS tests
          command: ./.circleci/run_tests.sh decidim-admin "time npm test -- decidim-admin"
      - run:
          name: Run admin RSpec
          command: ./.circleci/run_tests.sh decidim-admin "cd decidim-admin && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  system:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run system JS tests
          command: ./.circleci/run_tests.sh decidim-system "time npm test -- decidim-system"
      - run:
          name: Run system RSpec
          command: ./.circleci/run_tests.sh decidim-system "cd decidim-system && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  proposals:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run proposals JS tests
          command: ./.circleci/run_tests.sh decidim-proposals "time npm test -- decidim-proposals"
      - run:
          name: Run proposals RSpec
          command: ./.circleci/run_tests.sh decidim-proposals "cd decidim-proposals && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  comments:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run comments JS tests
          command: ./.circleci/run_tests.sh decidim-comments "time npm test -- decidim-comments"
      - run:
          name: Run comments RSpec
          command: ./.circleci/run_tests.sh decidim-comments "cd decidim-comments && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  meetings:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run meetings JS tests
          command: ./.circleci/run_tests.sh decidim-meetings "time npm test -- decidim-meetings"
      - run:
          name: Run meetings RSpec
          command: ./.circleci/run_tests.sh decidim-meetings "cd decidim-meetings && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run pages JS tests
          command: ./.circleci/run_tests.sh decidim-pages "time npm test -- decidim-pages"
      - run:
          name: Run pages RSpec
          command: ./.circleci/run_tests.sh decidim-pages "cd decidim-pages && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  results:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run results JS tests
          command: ./.circleci/run_tests.sh decidim-results "time npm test -- decidim-results"
      - run:
          name: Run results RSpec
          command: ./.circleci/run_tests.sh decidim-results "cd decidim-results && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  budgets:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run budgets JS tests
          command: ./.circleci/run_tests.sh decidim-budgets "time npm test -- decidim-budgets"
      - run:
          name: Run budgets RSpec
          command: ./.circleci/run_tests.sh decidim-budgets "cd decidim-budgets && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
  surveys:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /code
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - run:
          name: Create test DB
          command: |
            cd spec/decidim_dummy_app/
            bundle install
            RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: cd /code
      - run:
          name: Run surveys JS tests
          command: ./.circleci/run_tests.sh decidim-surveys "time npm test -- decidim-surveys"
      - run:
          name: Run surveys RSpec
          command: ./.circleci/run_tests.sh decidim-surveys "cd decidim-surveys && time bundle exec rake"
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - main:
          requires:
            - build
      - core:
          requires:
            - build
      - assemblies:
          requires:
            - build
      - api:
          requires:
            - build
      - processes:
          requires:
            - build
      - admin:
          requires:
            - build
      - system:
          requires:
            - build
      - proposals:
          requires:
            - build
      - comments:
          requires:
            - build
      - meetings:
          requires:
            - build
      - pages:
          requires:
            - build
      - results:
          requires:
            - build
      - budgets:
          requires:
            - build
      - surveys:
          requires:
            - build
